$(function(){
	$('.scroll-home').on('click',function(){
		$('html').animate({
			scrollTop:$('header').offset().top()
		},500)
	})
	$('.scroll-about').on('click',function(){
		$('html').animate({
			scrollTop:$('#about').offset().top
		},1000)
	})
	$('.scroll-services').on('click',function(){
		$('html').animate({
			scrollTop:$('#services').offset().top
		},1000)
	})
	$('.scroll-team').on('click',function(){
		$('html').animate({
			scrollTop:$('#team').offset().top
		},1000)
	})
	$('.scroll-portfolio').on('click',function(){
		$('html').animate({
			scrollTop:$('#portfolio').offset().top
		},1000)
	})
	$('.know_more').on('click',function(){
		$('html').animate({
			scrollTop:$('nav').offset().top
		},1000)
	})
	$('.scroll-contact').on('click',function(){
		$('html').animate({
			scrollTop:$('#contact').offset().top
		},1000)
	})
	$('.scroll-home').on('click',function(){
		$('html').animate({
			scrollTop:$('header').offset().top
		},1000)
	})
	$(window).on('scroll',function(){
		if($(window).scrollTop()>=100){
			$('.scr-top').fadeIn().css('display','flex');
		}
		else {
			$('.scr-top').fadeOut();
		}
	})
	$('.scr-top').on('click',function(){
		$('html').animate({
			scrollTop:0
		},1000)
	})
})